### ISSUE TITLE
After save fails, save icons become disabled, and there is no warning when editor is closed

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#105]
If editor is unable to save the file (for example, if the file is open in another application) then it prints this warning...
`ERROR> Aug 24 08:55:59 TFormScxmlGui::actSaveAllExecute> Cannot create file "C:\data\filename.scxml". The process cannot access the file because it is being used by another process`

Even though the save failed, the save icons become grayed out (as if there are no changes and save is not necessary) .
Also, when the application is closed, there is no warning that the content was not saved.

**Comment by alexzhornyak** [comment]
Good catch, will fix in the next release
