### ISSUE TITLE
Feature request: Allow finer control of auto-complete

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#106]
Currently auto-complete is very aggressive and kicks in too fast when typing comments and scripts.
Add a setting to control the delay before auto-complete kicks in.
Add the ability to temporarily turn off auto-complete, either by hot-key or by a button on a toolbar.
Maybe add an option to always turn off autocomplete in comment type fields?

**Comment by alexzhornyak** [comment]
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/e5eda6e9-e6aa-48d3-b868-595cd62ac555)

The only thing I can do is to expose **CompletionTimeoutEnabled** option. When the option is disabled, you would press Ctrl + Space to manually call Auto Complete
