### ISSUE TITLE
When creating internal "catch-all" transitions, arrow doesn't snap to edge

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#107]
ScxmlEditor v2.5.1.1749
The arrow is connected to the shape, and moves with it, but it doesn't snap to the edge like normal transitions.  The logic works properly, it is just a graphical issue.
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/111876711/1f0d4449-e94c-44e5-94fb-c74326f30aa6)

**Comment by alexzhornyak** [comment]
I can confirm it. As a temporary workaround I offer to pin connection to the middle or up/bottom corner of the shape

https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/ba0a12e0-a87d-405d-9a5a-8c38b2d53ee2

**Comment by EdK-z** [comment]
Thanks, that's an acceptable workaround.  Why is the issue labeled as "invalid"?

**Comment by alexzhornyak** [comment]
When 'Adjusted sides' option is set, connection must be auto fit to the edge of the shape after point drag is completed, so the behaviour is invalid in this case
