### ISSUE TITLE
Any way to increase transition arrow line's width beyond an infinitesimal?

### ISSUE THREAD

**Issue by enjoysmath** [alexzhornyak/ScxmlEditor-Tutorial#113]
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/1606391/da190e06-d495-4223-afee-6e718234bd7d)

Looked in all options in whole app, didn't see line width or border width that effected it.   Thx 😎

**Comment by alexzhornyak** [comment]
Hi, currently transition settings are hardcoded. I am planning to add them to Theme Settings. You can take a look what a present there:
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/6068e776-2c02-4b50-8c86-f939c5265d1f)

I will add transition settings there
