### ISSUE TITLE
[scxmlexternmonitor.h] Undeclared identifier 'L' on Linux

### ISSUE THREAD

**Issue by Eugene-Red** [alexzhornyak/ScxmlEditor-Tutorial#40]
Hi, I'm trying to debug statechart, located on Linux machine and I'm getting an error **`Undeclared identifier 'L'`** during compilation with GCC compiler on macro definition line
```cpp
#define MLOG(VAL)	std::wcout << L#VAL << "> " << QDateTime::currentDateTime().toString("HH:mm:ss.zzz").toStdWString() << " QtScxmlTester.exe "
```

P.S. This line is compiled successfully with MSVC

**Comment by alexzhornyak** [comment]
'scxmlexternmonitor.h' is fixed but since ScxmlEditor version 2.1.5 is deprecated!!!
Use ['scxmlexternmonitor2.h'](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/tree/master/Include) instead!!!
