### ISSUE TITLE
Autocomplete for events

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#73]
Feature request
Would it be possible to add autocomplete for \<transition>, \<send> and \<raise> events?  Currently its too easy to accidentally mistype a character when generating an event, making it difficult to find why something isn't working in complex charts.
Alternately, maybe create a new window that shows a list of all unique \<transition>, \<send> and \<raise> statements throughout the entire chart in alpha order.  This would make it easier to spot small typing mistakes.  This could also then be used to maybe auto-generate triggers.

**Comment by alexzhornyak** [comment]
![image](https://user-images.githubusercontent.com/18611095/186196962-53923f01-8ced-4cce-9d0b-f57b0775b6b2.png)

You can use Structure View with filtering for now. You can check names there

![image](https://user-images.githubusercontent.com/18611095/186197498-86d8e93d-5722-44f7-96b3-fd3c4503cdec.png)
