### ISSUE TITLE
Undo resets changes in appearance

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#75]
If I "edit appearance" of a transition and change the text, then do other work, then undo anything, the edited appearance resets to its original content.
Steps to reproduce:
1) Create two states
2) Create a transition between the states
3) Put a condition in the transition (any text, doesn't really matter) - the transition will show the condition text
4) Edit the appearance of the transition to change the displayed text to something else (just the appearance, not the actual condition)
5) Create two more states
6) Hit undo once
Expected: Only the last change (last state added) is removed
Actual: Last change is removed and transition appearance resets to show the condition text (edited appearance text is lost)

**Comment by alexzhornyak** [comment]
Do not edit transition content in appearance. It should be readonly and the next app versions, memo control will be locked for editing

![image](https://user-images.githubusercontent.com/18611095/186514385-444bb650-0ed0-4999-b119-530b71c7297a.png)

Edit either in PropertyInspector, or Double Click on transition and edit in Transition Editor

![image](https://user-images.githubusercontent.com/18611095/186514732-8ce35e89-c8a3-48f4-a7bf-44f77a55996d.png)

**Comment by EdK-z** [comment]
The intent is to edit the visual appearance of the object, not the content.
For example, I have something like this which contains a long comment.
![image](https://user-images.githubusercontent.com/111876711/186523391-8ab41dc3-91aa-4aee-af5a-c113e17c342b.png)
I don't want to change the content of the condition, I just want it to look like this:
![image](https://user-images.githubusercontent.com/111876711/186523649-bc472ef1-299b-43c8-b7fc-e90431d0fde2.png)

**Comment by alexzhornyak** [comment]
https://user-images.githubusercontent.com/18611095/186529213-ba429523-79c3-4599-85f1-65ad3b08de72.mp4

P.S. I don't like comments inside conditions. For example: 'transition as soon as conditions are met' is absolutely useless. Chart must be as most as possible easy for "eye reading". You can create \<comment\> node and put there any additional info. Attach it to the state that is a source.

Here is an example:
![image](https://user-images.githubusercontent.com/18611095/186529766-105f893e-eac7-46f3-9aa7-6617648134e6.png)
