### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#78]
Feature request
Please add an autosave feature.  I just did something that caused the app to get into a state where it failed to save my work.  Lost a couple of hours of work.  Fortunately, I was able to capture an SVG, but saving the project and SCXML failed.

**Comment by alexzhornyak** [comment]
Since 2.3.1 it is available to revert State Chart from the last written cache

![image](https://user-images.githubusercontent.com/18611095/214337734-cbaf6927-1b27-494b-a283-2e38ad61f44e.png)
