### ISSUE TITLE
Structure view search can't find certain constructs sometimes?

### ISSUE THREAD

**Issue by EdK-z** [alexzhornyak/ScxmlEditor-Tutorial#79]
Defect?
Transitions with conditions starting with underscore can't be found in structure view sometimes (? it works on a completely new chart, but fails on my fairly complex chart )...
`_event.data.something == theThing`
That will fail to find any part of that condition, it won't find "_event", it won't even find "theThing" in structure view (but it will find both in a general search)
![image](https://user-images.githubusercontent.com/111876711/189377653-97ddb37d-e5cf-48a6-a29d-b602767f5c63.png)

btw... I'm actually using _event in a lot of places everywhere, the image just shows one example, but it should be matching a whole lot of items.
Sorry, can't share my actual chart.

**Comment by alexzhornyak** [comment]
Structure View performs string-search in Tree View. Transition is represented in short way there.
So, if you need deep search through all chart, you need to use Ctrl + F (Find operation)

https://user-images.githubusercontent.com/18611095/189491040-6ccebf61-8415-43f3-98b6-b90c4cc0e58b.mp4

**Comment by EdK-z** [comment]
I understand, thanks.
