### ISSUE TITLE
qt compatibility

### ISSUE THREAD

**Issue by larry104** [alexzhornyak/ScxmlEditor-Tutorial#88]
How can one add tags which are required by qt to the scxml file e.g.
`<!-- enable-qt-mode: yes -->`

**Comment by alexzhornyak** [comment]
There is no option to generate qt metainformation automatically. Only manually by using comment node and extra content node

**Comment by larry104** [comment]
The problem is that the comment node and extra content node only allow me to add xml inside the scope of <scxml>..</scxml> not outside where qt expects it. Also, it seems the ScxmlEditor does not like the syntax of 
`<!-- enable-qt-mode: yes -->`
and gives an error.
`ERROR> Apr 03 09:37:44 ExtraContent in shape [ExtraContentShape1__40E5FB6BF7967CAF][extracontent {<!-- enable-qt-mode: yes -->}] XML format is invalid[<!-- enable-qt-mode: yes -->]`

**Comment by alexzhornyak** [comment]
1. This video shows how to use comment nodes

https://user-images.githubusercontent.com/18611095/229579717-5d33f073-349b-4adc-a534-60440f0f6e38.mp4

2. This video shows how to use extracontent nodes

https://user-images.githubusercontent.com/18611095/229579793-032ff860-5ca8-4dc7-811a-5a7136f00493.mp4

**Comment by larry104** [comment]
That works like a charm at qt picks it up properly even inside the <scxml> scope ... Thanks!!!
