### ISSUE TITLE
Saving when editing a scxml in a virtual state

### ISSUE THREAD

**Issue by larry104** [alexzhornyak/ScxmlEditor-Tutorial#89]
It seems there is no save available when editing scxml in a virtual state. I just added the transitions in the editor and press convert. The drawing gets updated but the save is still grayed out. 

![image](https://user-images.githubusercontent.com/2013720/234984456-4ff609d1-a519-4e7e-971c-4c7f33e1f7e4.png)

**Comment by alexzhornyak** [comment]
I can confirm that manual edit does not trigger an update

To solve this you can use Force Save Unit option

![image](https://user-images.githubusercontent.com/18611095/234987591-2bf84033-5883-433e-8a95-03a4b346bcbf.png)

**Comment by alexzhornyak** [comment]
P.S. Also would like to remind that there is copy-paste transitions option. So in my pipeline I almost never use manual scxml edit.

https://user-images.githubusercontent.com/18611095/234989339-2c199a80-78c7-4f3e-b24b-8ab0a496672a.mp4

**Comment by larry104** [comment]
The reason why I use the editor is because I have 24 states and every state can transition into any other state. Unfortunately, that can't be displayed anymore and the autodraw/route has really problems showing anything meaningful.

**Comment by alexzhornyak** [comment]
If you want, you can send me your state chart for code review private or public. I'll take a look whether is it possible to optimize

**Comment by larry104** [comment]
It looks kind of like this ... 

`
<scxml datamodel="ecmascript" name="ScxmlOutputSelect" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<parallel id="OutputSelect">
		<state id="O1">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
         </state>
		<state id="O2">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
		<state id="O3">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
   	</state>
		<state id="O4">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
		<state id="O5">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
		<state id="O6">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O7">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O8">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O9">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O10">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O11">
            <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
      	<state id="O12">
             <transition event="O1_pressed" cond="In('o1_o6')" target="O1"/>
            <transition event="O2_pressed" cond="In('o1_o6')" target="O2"/>
            <transition event="O3_pressed" cond="In('o1_o6')" target="O3"/>
            <transition event="O4_pressed" cond="In('o1_o6')" target="O4"/>
            <transition event="O5_pressed" cond="In('o1_o6')" target="O5"/>
            <transition event="O6_pressed" cond="In('o1_o6')" target="O6"/>
            <transition event="O1_pressed" cond="In('o7_o12')" target="O7"/>
            <transition event="O2_pressed" cond="In('o7_o12')" target="O8"/>
            <transition event="O3_pressed" cond="In('o7_o12')" target="O9"/>
            <transition event="O4_pressed" cond="In('o7_o12')" target="O10"/>
            <transition event="O5_pressed" cond="In('o7_o12')" target="O11"/>
            <transition event="O6_pressed" cond="In('o7_o12')" target="O12"/>
		</state>
	</parallel>
</scxml>
`

**Comment by larry104** [comment]
About the copy and paste of a transition ... I can't really tell from the video what exactly you do. Could you describe it in words how to do that? But that seems super useful!!!

**Comment by larry104** [comment]
Wow, I have to admit this is super clever!! What I don't understand is why reenters the same state when pressing the same number. It should never leave the O.x state when the same number is pressed since the transition to check is the negated condition? But when switching the trigger to ctaEdit and triggering the same condition it does go actually back and forth into the same O state. I mean it's exactly what I need but I don't understand why it does it. 

As for the copy paste, that was strange but that is what I tried yesterday. Hmm. But, yes that works super!

**Comment by larry104** [comment]
Is there a trick to send an event from a invoked state machine within an invoked state machine all the way to the top so I can catch it on the c++ side? The `target="#_parent"` sends it only one level up and when I catch the event on the next level and send that to it's parent I get an endless loop of the same event.

**Comment by alexzhornyak** [comment]
You need to disable ['autoforward' attribute of \<invoke\> element](https://alexzhornyak.github.io/SCXML-tutorial/Doc/invoke.html#autoforward) and you need to send events to child machines using target `#_ + SUBMACHINE_ID`

### Example:
In this example parent and child machine will generate the same events and we need to convince that they do not affect each other
**parent.scxml**

![image](https://user-images.githubusercontent.com/18611095/236664357-10ac555b-db1a-4f78-a0cb-64f189810f23.png)

**child.scxml**

![image](https://user-images.githubusercontent.com/18611095/236664412-c4c59b4e-6e5e-47ed-a8d6-8b46037d3d31.png)

**Output:**
```
[Log] CHILD COUNT: 0
[Log] PARENT COUNT: 0
[Log] CHILD COUNT: 1
[Log] PARENT COUNT: 1
[Log] CHILD COUNT: 2
[Log] PARENT COUNT: 2
[Log] CHILD COUNT: 3
[Log] PARENT COUNT: 3
...
```

[InvokeAutoForward.zip](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/files/11414199/InvokeAutoForward.zip)

**Comment by larry104** [comment]
Thanks a lot! What's interesting in case I have only one level of nesting like in your example Parent -> Child1 and if I have autoforward = true and send from the Child1 to the #_parent I don't get a recursive loop. 

But if I have a deeper nesting like Parent -> Child1 -> Child2 and send from Child2 to it's #_parent (Child1) and then from Child1 to #_parent (Parent) I get a recursive loop. Let me play with this a little bit more.

**Comment by alexzhornyak** [comment]
In my example if you change  to autoforward,  timings will be broken, instead of 1 sec delay, it will trigger in wrong time, because child will get parasite parent events

**Comment by larry104** [comment]
I get that autoforward is dangerous. 

Your example looks like what I did in case S1 (I think, but maybe I missed something). But, what I rather need is the implementation of case S2 as S1 and S2 should run in parallel. The reason why I have 3 levels of hierarchy is that on the keyboards_statemachine.scxml level  I will have S1, .., S18, and on the keyboard.scxml level I will have KB1,.., KB18 and in key.scxml I will have a pretty complex logic . This example is of course very simplified.  In this test I just tried to pass events all the way down to key.scxml (with autoforward set to false). key.scxml will later need to send events to turn on/off LEDs all the way back to the top so I can set these on the c++ side. So, key strokes go down the hierarchy and other event will need go back up the hierarchy.  For some reason events send to ID_CHILD_S1/S2 are not forwarded  not even in the S1 case which looks like your example. Probably some stupid mistake on my side but I can't find why .. ;-(
[Test.zip](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/files/11416210/Test.zip)

**Comment by alexzhornyak** [comment]
1) 'event' attribute in \<send\> element is a string param
![image](https://user-images.githubusercontent.com/18611095/236731184-233b3433-a136-4913-bbb8-8839bd9b7550.png)

2) forwarded event must be like this
```xml
<send eventexpr="_event.name" target="#_ID_CHILD_S1">
	<content expr="_event.data"/>
</send>
```

3) in keyboard.scxml you are forwarding event only to KB1
![image](https://user-images.githubusercontent.com/18611095/236731887-d8f14f6c-b5ca-4ede-82df-74e469ec8c3e.png)
![image](https://user-images.githubusercontent.com/18611095/236731984-4506afd3-92bd-4c30-8f94-519c0a7226f4.png)

You can use \<foreach\> element to send events to all submachines:
```xml
<foreach array="['ID_CHILD_KB1', 'ID_CHILD_KB2']" index="index" item="item">
	<send eventexpr="_event.name" targetexpr="'#_' + item">
		<content expr="_event.data"/>
	</send>
</foreach>
```

P.S. You can use Simple smart connection if two states have transition with the same name and condition
![image](https://user-images.githubusercontent.com/18611095/236733207-17deed33-0ec6-4094-bf9b-ef1982a23681.png)

[Test.zip](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/files/11417624/Test.zip)

**Comment by larry104** [comment]
Yeah makes sense. I can't believe I missed that. Thank so you much for all your help!

I was wondering if there is a way that history states can be saved on file ... or how do people store the state of an entire state machine so you can continue where you left off when you restart the application?

**Comment by alexzhornyak** [comment]
It is called state machine serialization and is present in some frameworks, for example [uscxml](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/Interpreter.h)

![Screenshot_20230508-210434_Chrome](https://user-images.githubusercontent.com/18611095/236897748-a064a9f7-2c30-4bba-bf3c-0d559ab9edca.jpg)

**Comment by larry104** [comment]
Thanks! ... that's cool and that would be real good reason to switch from qscxmlc to uscxml

**Comment by larry104** [comment]
Unfortunately, there seem to be problems with qtscxml 6.5 after all.  Sending to #_invokeid does not seem to work properly. In Case 1 I see the leds going off in case 2 not. I tried to compile uscxml but unfortunately that does not compile on Ubuntu 22.04.  I filed and issue but it seems it's stale. 

`<send event="set.led.S1.1.Off"/>
<send event="set.active" target="#_ID_CHILD_S1">
  <content expr="0"/>
</send>`

`<send event="set.active" target="#_ID_CHILD_S1">
  <content expr="0"/>
</send>
<send event="set.led.S1.1.Off"/>`

**Comment by alexzhornyak** [comment]
I am not sure that this is Qt problem. 

You can compile Qt testing application for ScxmlEditor in Qt 6.5, add it in properties and compare with 5.15
https://github.com/alexzhornyak/ScxmlEditor-Tutorial/tree/master/Testers/QtScxmlTester

Regarding uscxml, I will take a look and give an answer there

**Comment by larry104** [comment]
Unfortunately, older version of qt were not able to invoke other state machines.  That at least was fixed and seems to work now in 6.5. It's really strange this error and I noticed that the log's were not printed after the send's to #_invokeid, sending to #_parent seems to work fine though.

**Comment by larry104** [comment]
I filed a [bug report](https://bugreports.qt.io/browse/QTBUG-113555) with qt. Let's see if this ever get fixed. In the meantime I got uscxml to work and the same test case runs just fine. 

Quick question ... is there a way in uscxml to tell when a statemachine is ready with initialization and in stable states?

**Comment by larry104** [comment]
I get interesting errors when loading invoked statemachines. It seems the loading is not finalized even though I put the invoke is in the parent. Is there a trick to force the loading of invoked statemachines to be done first before entering into any state?
`
[Error]   Platform Event 
    "name": error.communication
    "data": {
      "cause": "Can not send to invoked component 'ID_CHILD_S1', no such invokeId", 
      "file":  "g:\\SDK\\uscxml_2_0\\src\\uscxml\\interpreter\\InterpreterImpl.cpp", 
      "line":  618
    }
`

![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/2013720/62ba5c82-97a6-413d-a5e9-77f172ee5b99)

**Comment by alexzhornyak** [comment]
Hi, the only correct way is to inform parent from invoked service that it is ready to communicate

![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/096a46be-d5dd-4905-9350-155b9eabcb59)

**Comment by larry104** [comment]
Thanks! That works perfectly.

Is there actually a way in the Scxml Editor to search and replace an event name globally?

**Comment by alexzhornyak** [comment]
https://alexzhornyak.github.io/ScxmlEditor-Tutorial/Doc/ChartDesignPanel.html#replace

**Comment by larry104** [comment]
Thanks again. "Chart design panel" was literally the last place I didn't check ;-) Since search & replace is an important topic you might want to consider adding a extra section in the table of contents.
