### ISSUE TITLE
v2.3.1.1712 - SVG output does not include transitions when curves are used

### ISSUE THREAD

**Issue by slave2sync** [alexzhornyak/ScxmlEditor-Tutorial#90]
Hello,
Thank you for this wonderful tool. I've defined some transitions in my diagram and used curves to draw them. When exported to SVG they don't show up (only the events and conditions are shown). I used all SVG export settings.

**Comment by alexzhornyak** [comment]
Hi, I can confirm it and will fix in the next release, thank you for a good catch
