### ISSUE TITLE
v2.3.1.1712 - Transition type is not saved in scxml in case of external transitions

### ISSUE THREAD

**Issue by slave2sync** [alexzhornyak/ScxmlEditor-Tutorial#91]
Hello
Thank you again for this great tool!
I've noticed that the transition type is not stored in the scxml in case of external transitions. The type is only stored in case of internal transitions. Could you perhaps add this?

**Comment by alexzhornyak** [comment]
Hi, transition type is external by default, so scxml frameworks that are standard-compliant do not require this default attribute to be present in the scxml file.

P.S. If you need it for some other reasons you can override it in **ExtraParams** property
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/1570cccd-dff6-486b-b2df-a096af644119)

**Comment by alexzhornyak** [comment]
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/e375b61e-76e1-4edb-b233-b038e1fefa24)

![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/82ef1a81-15b9-482f-a1bc-d6f3b535570a)

![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/e73df4dd-6b4a-418f-aa60-f61ff7db74bb)
