### ISSUE TITLE
v2.3.1.1712 - Unable to set the color of states

### ISSUE THREAD

**Issue by slave2sync** [alexzhornyak/ScxmlEditor-Tutorial#92]
In this version I am unable to change the background color of states and/or the border color. All the state property widgets seem to be functional but no color change is done the background and the border colors.
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/626940/4406fd64-7a4e-4450-bbad-a8618ba02f7a)

**Comment by alexzhornyak** [comment]
Hi, unfortunately some colors are hardcoded. It is in plans to implement color themes. So will add it in the future

**Comment by alexzhornyak** [comment]
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/4ce9509e-86ad-4a42-a7f9-9bd6c59202cd)

Scxml, Parallel, Virtual state colors and border colors could be adjusted from Edit Appearance menu
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/2623d5ef-d644-499b-8d0a-b99a003baf71)
