### ISSUE TITLE
v2.3.1.1712 - Unable to load transitions from QT SCXML Editor files if state names or transition names contain spaces

### ISSUE THREAD

**Issue by slave2sync** [alexzhornyak/ScxmlEditor-Tutorial#93]
Hello,
I've created a really big state diagram using the QT SCXML editor. In that diagram I have state names and event names containing space characters. When I tried to import that unit (using Add existing Unit) into ScxmlEditor none of the transitions import correctly. 
Interestingly, ScxmlEditor doesn't seem to have an issue loading its own scxml files if they contain space characters.

To reproduce, I created two very simple diagrams using QT. The first (qt_simple1) does not contain space characters, the second (qt_simple2) does. Shown below is the second diagram containing spaces. 
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/626940/a4e5b66a-cf56-46eb-81cc-c7b4d5e31419)

The first parses correctly in ScxmlEditor, the second doesn't.
The log file contains the following error:
ERROR> May 19 12:28:56 LOAD_SCXML> Can not create transition from:[State 1] to:[State] event:[Transition 3] cond:[]
[qt_simple1.scxml.txt](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/files/11515537/qt_simple1.scxml.txt)
[qt_simple2.scxml.txt](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/files/11515538/qt_simple2.scxml.txt)

**Comment by alexzhornyak** [comment]
1. According to [SCXML standard](https://www.w3.org/TR/scxml/#state) state identifier must be a valid XML Schema ID, **which does not allow whitespaces** in their names.

2. Transition target can be a [**set of states**](https://www.w3.org/TR/scxml/#LegalStateConfigurations)
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/18611095/72827c76-0add-4fdf-8514-2d4c7fdfd228)

So parser split transition target with the space delimiter as a set of state IDs and that's why error happens

**Comment by slave2sync** [comment]
I wasn't aware that the space character is used as a delimiter to denote multiple targets! 
Out of curiosity though, do you thing that it would be valid to have the following:
<transition event="Transition_3" target="State_2 State_4" ?
Where State_4 is another state. 
If this is valid, what does it imply for the execution? That you have a synchronous transition from State_1 to both State_2 and State_4?

**Comment by alexzhornyak** [comment]
> The 'target' attribute of a <transition> (or the 'initial' attribute of a <state> or <scxml> element) do not in the general case specify a full legal state configuration since 1) they can contain <parallel> or non-atomic <state> elements 2) they do not contain the ancestors of the states in the list. We therefore define a legal state specification to be a set of states such that 1) no state is an ancestor of any other state on the list, and 2) a full legal state configuration results when all ancestors and default initial descendants have been added. (Note that the process of adding default initial descendants is recursive, since the 'initial' value may itself be non-atomic.) In a conformant SCXML document, the value of an 'initial' attribute or the 'target' of a <transition> must either be empty or contain a legal state specification.

This is from the docs by the link I've provided upper
