### ISSUE TITLE
Is it possible to add option to display self transitions within the state?

### ISSUE THREAD

**Issue by slave2sync** [alexzhornyak/ScxmlEditor-Tutorial#94]
I wanted to ask if it would be possible to provide an option in the settings to display self transitions within the state (as a list) instead of rendering them outside the state with lines. This could significantly enhance readability when reviewing really big state charts.

```
<state id="state1">
  <transition event="again" target="state1"/>
</state>
```
PS. A possible way to implement this is like the QT Statechart Editor
![image](https://github.com/alexzhornyak/ScxmlEditor-Tutorial/assets/626940/edea7590-949c-4e6f-85cd-f800b93a7f80)

**Comment by alexzhornyak** [comment]
Hi, I think it could be done as alternative self-transitions view, so by default it will be like is existing and could be switched to compact view. Will add it in the next release

**Comment by alexzhornyak** [comment]
https://alexzhornyak.github.io/ScxmlEditor-Tutorial/Doc/Transitions.html#self-transitions-inside-states
